services:
  melo-converter:
    build: .
    container_name: melo-converter
    expose:
      - "5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./downloads:/app/downloads
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - melo-converter

  nginx:
    image: nginx:latest
    container_name: nginx-reverse
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - melo-converter
