services:
  melo-converter:
    build: .
    container_name: melo-converter
    expose:
      - "5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./downloads:/app/downloads
    restart: unless-stopped